"""Add training_sessions user_sport_configs micro_cycle_configs

Revision ID: 9229418a85de
Revises: 001
Create Date: 2026-02-07 19:06:44.889885+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # Import SQLModel for custom types
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9229418a85de'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('micro_cycle_configs', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('computed_length_days', sa.Integer(), nullable=False),
                    sa.Column('override_length_days', sa.Integer(), nullable=True),
                    sa.Column('min_rest_days', sa.Integer(), nullable=False),
                    sa.Column('current_cycle_start', sa.Date(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_micro_cycle_configs_user_id'), 'micro_cycle_configs', ['user_id'], unique=True)
    op.create_table('training_sessions', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False), sa.Column('date', sa.Date(), nullable=False),
                    sa.Column('sport_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
                    sa.Column('session_order', sa.Integer(), nullable=False),
                    sa.Column('intensity_modifier', sa.Float(), nullable=False),
                    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
                    sa.Column('sport_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
                    sa.Column('load_metabolico', sa.Float(), nullable=False),
                    sa.Column('load_neuromuscolare', sa.Float(), nullable=False),
                    sa.Column('load_tendineo', sa.Float(), nullable=False),
                    sa.Column('autonomic_load', sa.Float(), nullable=False),
                    sa.Column('coordination_load', sa.Float(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ), sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id', 'date', 'sport_id', 'session_order',
                                        name='uq_training_user_date_sport_order'))
    op.create_index(op.f('ix_training_sessions_date'), 'training_sessions', ['date'], unique=False)
    op.create_index(op.f('ix_training_sessions_sport_id'), 'training_sessions', ['sport_id'], unique=False)
    op.create_index(op.f('ix_training_sessions_user_id'), 'training_sessions', ['user_id'], unique=False)
    op.create_table('user_sport_configs', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('sport_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
                    sa.Column('sessions_per_cycle', sa.Integer(), nullable=False),
                    sa.Column('custom_stress_profile', postgresql.JSON(astext_type=sa.Text()), nullable=True),
                    sa.Column('priority', sa.Integer(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ), sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id', 'sport_id', name='uq_user_sport'))
    op.create_index(op.f('ix_user_sport_configs_user_id'), 'user_sport_configs', ['user_id'],
                    unique=False)  # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sport_configs_user_id'), table_name='user_sport_configs')
    op.drop_table('user_sport_configs')
    op.drop_index(op.f('ix_training_sessions_user_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_sport_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_date'), table_name='training_sessions')
    op.drop_table('training_sessions')
    op.drop_index(op.f('ix_micro_cycle_configs_user_id'), table_name='micro_cycle_configs')
    op.drop_table('micro_cycle_configs')  # ### end Alembic commands ###
